name: PetsPlugin
version: '${project.version}'
main: com.github.gavvydizzle.petsplugin.PetsPlugin
api-version: 1.19
softdepend: [MineRewards, PlayerLevels, PrisonEnchants, RewardsInventory]
depend: [ServerUtils, WorldGuard]
authors: [GavvyDizzle]
commands:
  petsadmin:
    description: PetsPlugin admin commands
    permission: petsplugin.admin
  pets:
    aliases: [pet]
    description: PetsPlugin player commands
    permission: petsplugin.player
    permission-message: Insufficient permission
